//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int logid { get; set; }
        public string logtype { get; set; }
        public string logcontent { get; set; }
        public string logip { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public string loguser { get; set; }
        public string logfree { get; set; }
    }
}
