//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebEntities : DbContext
    {
        public WebEntities()
            : base("name=WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Blogs> Blogs { get; set; }
        public DbSet<Essays> Essays { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<PhotoGroups> PhotoGroups { get; set; }
        public DbSet<Photos> Photos { get; set; }
        public DbSet<Sources> Sources { get; set; }
    }
}
